version: '3.0'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - home-library-service-network

networks:
  home-library-service-network:
  driver: bridge
