version: '3.1'

services:
  db:
    build: ./prisma/
    container_name: 'hls-data-base'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - home-library-service-network

  app:
    build: .
    container_name: 'hls-app'
    volumes:
      - ./src:/app/src
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - home-library-service-network

networks:
  home-library-service-network:
    driver: bridge

volumes:
  db_data:
    driver: local
