version: '3.8'
services:

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

volumes:
  postgres:
